services:
  flask_app:
    build: .
    env_file:
      - .env
    expose:
      - "5000"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/src/app/static
    ports:
      - "80:80"
    depends_on:
      - flask_app
    restart: always